name: Build, Test, Publish

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:
    branches: [master]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 3.1
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'

      - name: Setup .NET SDK 6.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Setup JRE 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          java-package: jre

      - name: Setup libssl1.1 required to run .NET 3.1
        shell: bash
        run: |
          curl -LOf https://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
          rm -f libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
          sudo cp /etc/ssl/openssl.cnf /etc/openssl-1.1-for-manual-override.cnf
          sudo sed -i 's/openssl_conf = openssl_init/#openssl_conf = openssl_init/g' /etc/openssl-1.1-for-manual-override.cnf

      - name: Build
        shell: pwsh
        run: ./build/scripts/build.ps1

      - name: Test
        shell: pwsh
        run: ./build/scripts/test.ps1
        env:
          OPENSSL_CONF: '/etc/openssl-1.1-for-manual-override.cnf'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: './tests/TestResults/coverage.opencover.xml'
          disable_search: true
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Publish
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
        shell: pwsh
        run: ./build/scripts/publish.ps1 -NugetApiKey "${{ secrets.NUGET_API_KEY }}"
