name: Build, Test, Publish

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:
    branches: [master]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET SDK 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Setup .NET SDK 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Setup libssl1.1 required to run .NET 3.1
        shell: bash
        run: |
          curl -LOf https://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
          rm -f libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb

      - name: Build
        shell: pwsh
        run: ./build/scripts/build.ps1

      - name: Test
        shell: pwsh
        run: ./build/scripts/test.ps1

      - name: Upload code coverage
        if: ${{ true }}
        uses: codecov/codecov-action@v2
        with:
          files: ./tests/TestResults/coverage.opencover.xml
          fail_ci_if_error: false
          verbose: true

      - name: Publish
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
        shell: pwsh
        run: ./build/scripts/publish.ps1 -NugetApiKey "${{ secrets.NUGET_API_KEY }}"
